m68kdasm.c
This is a fix for disassembly of the "cas" instruction. The current code expects the second register to be bit 8 but it's actually on bit 6 (this according to the M68000 FAMILY PROGRAMMER’S REFERENCE MANUAL 4-67) and I have also verify in my tests that this fixes the bug I saw when testing this.
Also fixed incorrect order if printing in bfexts, bfextu and bfffo
=> Bug fix for cas disassembly

m68k_in.c
This PR fixes a bug in the adjustments made to the m68ki_cycles
table, for all shift operations with known shift distance (where the
shift distance is encoded in the instruction word).
More specifically, the expression "ostruct->cycles[k] + ((((j-1)&7)+1)<<1)" on line 217 had two problems; It's accessing the ostruct->cycles array out-of-bounds (as **k** is now 3) which happened to return zero, and also **j** is the wrong value for the in-instruction shift count (it represents DY here), the correct value is located in **i**.
Affects cycle counts for **ASL/ASR, LSL/LSR, ROL/ROR** and **ROXL/ROXR** on the
68000 and 68010 emulations.
=> Fix incorrect cycle counts for some bit-shift ops

m68k_in.c
The ADDA _ea_, An instruction (both word and long variants) must
evaluate the source operand before the destination operand (_ea_ before
An), because in case of pi/pd addressing modes, the increment/decrement
side-effect to AY must happen **before** reading AX if both AX and AY
references the same register!
As an example, the operation ADDA.L (A0)+, A0 needs to be evaluated like;
mem = read_long(A0);
A0 += 4; // post-increment A0
A0 += mem;
but now it might (explained below) be evaluated like;
reg = A0
mem = read_long(A0);
A0 += 4; // post-increment A0
A0 = reg + mem;
which overwrites the side-effect, and degenerates into ADDA.L (A0), A0.
Similarily ADDA.L -(A0), A0 degenerates into ADDA.L (-4, A0), A0.
ADDA.W is also affected in the same way. Expected ADDA behaviour was also …
=> Fix ADDA operand evaluation order

m68k_in.c
@emoon noticed that the operand evaluation order issue, fixed for ADDA in #10 was also present in SUBA. This PR contains the same fix for SUBA. I looked quickly at the other xxxA instructions as well but couldn't find any further issues.
The SUBA _ea_, An instruction (both word and long variants) must
evaluate the source operand before the destination operand (_ea_ before
An), because in case of pi/pd addressing modes, the increment/decrement
side-effect to AY must happen before reading AX if both AX and AY
references the same register!
=> Fix SUBA operand evaluation order

m68k_in.c
This PR modifies cycle counts for the DBF instruction, which previously was a fixed 14 cycles, to  consume either 10 or 14 cycles depending on if the branch was taken (10), or not (14). 
This is consistent with the behaviour of the other DBcc instructions, as well as when compared with EASy68k and current MAME Musashi, see [the DBF entry in M68KMAKE_TABLE_BODY](https://github.com/mamedev/mame/blob/master/src/devices/cpu/m68000/m68k_in.cpp#L550) and [M68KMAKE_OP implementation for DBF](https://github.com/mamedev/mame/blob/master/src/devices/cpu/m68000/m68k_in.cpp#L4501-L4505)
=> Fix cycle count for DBF instruction

m68k_in.c, m68kcpu.c, m68kcpu.h
The Scc instruction with a register operand takes two extra cycles when
the condition is true, on the 68000. On the 010/020 there are no such
penalty. 
There was already the macro CYC_SCC_R_FALSE, and a backing field, which was set to 2 for the 000, but it wasn't used in the Scc template, so I renamed that (and the backing field) to CYC_SCC_R_TRUE, and used that in the Scc template.
=> Fix incorrect Scc cycle count

m68kmake.c
According to the M68000UM, JMP 32 ix should take 14 cycles, not 12, for
both the 68000 and 010. 
(A base cost of 4 is added to the value in the table, that's why it says 10, not 14)
=> Fix JMP_32_IX cycle count

m68kcpu.c
Or resetting when CPU_INSTR_MODE is set to INSTRUCTION_NO affects what
is pushed by address errors even after calling m68k_init,
m68k_set_cpu_type, and m68k_pulse_reset.
=> Reset CPU_INSTR_MODE in m68k_pulse_reset

m68kcpu.h
Ok so this PR is perhaps a bit pedantic. But when running tests comparing instructions in [r68k](https://github.com/marhel/r68k), Musashi sometimes reported consuming an odd number of cycles for jump instructions!
After some investigation this was explained by the following;
When an branch/jump instruction is jumping back to itself,
USE_ALL_CYCLES should not set m68ki_remaining_cycles to zero, because
that optimization reports more cycles spent than would have been
consumed without the optimization. If the jump takes N cycles, and
m68ki_remaining_cycles is not an multiple of N, then we want to spend
just a multiple of N and leave the remainder (m68ki_remaining_cycles % N
cycles). Setting to zero spends extra cycles corresponding to the
remainder.
After executing the jump, m68k_execute …
=> Don't let USE_ALL_CYCLES overspend cycles

m68k_in.c
This PR fixes MOVEM cycle counts for all 16/32-bit addressing modes for the 000 and 010, except pi, pd, and 16-bit pcdi/pcix which were already correct, as they require separate implementations and were listed separately. 
Previously most addressing modes used 4 (16-bit) or 8 (32-bit) cycles too much. 32-bit pcdi/pcix was off by 4. 
The explanation for this is likely that cycle counts in m68k_in.c are representative for the minimum An/Dn base case, and additional addressing mode cycle costs are added elsewhere per mode to get cycles for a particular instruction and a particular addressing mode.
But no An/Dn base case is available for MOVEM, so the data were likely from the "address indirect" mode, causing an additional cost of 4 or 8 cycles for all addressing modes in the "." case in the …
=> Fix MOVEM cycle-counts

m68kmake.c
This PR adjusts the AI mode of PEA to use 12 cycles instead of 10, for the 68000 and 010.
According to MC68000UM, the AI mode of PEA uses 12 cycles (not 10) on the
68000 (see Table 8-10) and 010 (see Table 9-16). The base case in the
handler table is 6 cycles, so 6 additional cycles is needed to end up
with 12. The adjustments for the other addressing modes were correct.
=> Fix pea_32_ai cycles

m68k_in.c
Much like #16 this PR is about not overspending cycles. However it's a bit more complicated in the case of STOP, which should (in supervisor mode) consume at least 4 cycles, but just consume any excess cycles if given more - as the processor enters the stopped state after 4 cycles. 
Given 1-4 cycles to execute a STOP, will consume 4 cycles (the cost of the stop instruction).
Given more than 4 cycles to execute a STOP, will consume all given cycles.
Just using USE_ALL_CYCLES() would (after #16) always consume multiples of 4, which doesn't seem right, as the processor is no longer executing any instructions after a successful STOP.
Without this PR, a STOP consumes all given cycles _plus_ 4 for the STOP - for example, given 6 cycles would consume 10.
=> Make STOP properly consume all cycles

m68kcpu.h
This PR fixes a cycle count issue during address errors, and if the address error depletes all remaining cycles, now returns from execution without executing further instructions.
The address error handler is called after a longjmp that does not pass the part of the excecute loop that deducts instruction cycles. This means we should not try to undo the instruction's cycles, as other exception handlers do, because this will incorrectly reduce the cost of the exception by the number of cycles for the current instruction.
For costly instructions like MUL and DIV, this will in effect result in a _net increase_ of available cycles. This could, I guess, result in an situation where available cycles for m68k_execute never runs out:
* an address error occurs during an expensive instruction, which …
=> Fix address error cycle count and cycle depletion behavior

m68kcpu.h
As trap exceptions are called from within a normal instruction handler
(as opposed to the address error handler that are called via a longjmp),
control will eventually return to the execution loop where the
instructions cycles will be deducted.
This PR adds the cycles for the instructions back to the available
cycles, or we will pay both the cost of the exception, and of the
instruction.
=> Undo instruction cycles in trap exception

m68kcpu.h
This PR looks very similar but deals with trap#n exceptions ;)
As trap#n exceptions are called from within a normal instruction handler
(as opposed to the address error handler that are called via a longjmp),
control will eventually return to the execution loop where the
instructions cycles will be deducted.
This PR adds the cycles for the instructions back to the available
cycles, or we will pay both the cost of the exception, and of the
instruction.
=> Undo instruction cycles in trap#n exception

m68kcpu.c
According to the M68000UM, the two unimplemented instruction exceptions
both cost 34 cycles, not 4.
Actually, that's a bit of a lie. Table 8-14. Exception Processing
Execution Times does not even mention unimplemented instruction
exceptions, but section 6.3.6 Illegal and Unimplemented Instructions
basically says that unimplemented instructions are just a special case
of illegal instructions in that they have separate exception vectors.
=> Fix unimplemented instruction cycles

m68kcpu.c
There was a conflict between Musahi's uint and OpenBSD's uint:
$ cc -o m68kmake m68kmake.c
$ ./m68kmake
$ cc -DM68K_COMPILE_FOR_MAME=0 -c m68kcpu.c
In file included from m68kcpu.c:565:
In file included from /usr/include/stdio.h:46:
/usr/include/sys/types.h:58:22: error: cannot combine with previous 'int'
declaration specifier
typedef unsigned int    uint;           /* Sys V compatibility */
^
./m68kcpu.h:75:25: note: expanded from macro 'uint'
#define uint   unsigned int
^
1 error generated.
=> Remove extra `#include <stdio.h>` to fix `uint`

m68kmake.c
`name` field in `struct opcode_struct` is an array,
so the condition is always false.
gcc warns:
```sh
$ gcc -o m68kmake -I. -Wall -Werror -DM68K_COMPILE_FOR_MAME=0 m68kmake.c
m68kmake.c:652:36: error: comparison of array 'op->name' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
for(op = g_opcode_input_table;op->name != NULL;op++)
~~~~^~~~    ~~~~
m68kmake.c:668:36: error: comparison of array 'op->name' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
for(op = g_opcode_input_table;op->name != NULL;op++)
~~~~^~~~    ~~~~
2 errors generated.
```
This change fixes potential error which accessing out of range.
=> Fix loop condition

m68k.h, m68kconf.h, m68kcpu.c, m68kcpu.h, m68kfpu.c, readme.txt
Hi ! Long time no see... !
Anyway it's about the illegal instruction callback I talked about.
The idea behind this is to be able to use the musashi files in a project and modify only m68kconf.h, otherwise it would be much faster to modify only m68kcpu.h for this (what I did last night).
The patch adds a ton of comment in m68kconf.h about that, I tested the 3 cases, the one with OPT_ON without wanting to actually... but anyway it works. As I said in the comment you should always put OPT_SPECIFY_HANDLER if you want to use it, it declares the handler as extern in this case to avoid a compilation error.
=> Illegal instruction callback

m68kdasm.c
when using read immediate mode for disassembly ( ie using m68k_read_disassembler_16 & co ), the disassembly is totally broken because of typo. Only 8bits of opcode is read instead of 16 or 32bits
=> fixed disassembly (completely broken in !g_rawop mode )

m68k.h, m68k_in.c, m68kcpu.c, m68kcpu.h
Pull in the bus error emulation support from philpem/freebee.
This might need a bit of clean-up work.
It's quite similar to address error emulation, except that the 68K (010 and later at least) allows instructions which cause bus-errors to be restarted after the fault is resolved. This is widely used for memory paging on e.g. the AT&T 3B1 / 7300 / UNIX PC.  (e.g. a bus error is raised due to an access to memory which isn't mapped/paged in -- the fault handler pages in the needed memory and returns, executing the instruction)
=> Add bus error emulation support

m68kmake.c
On some architectures, memcpy uses optimisations which break when the
buffer pointers overlap. Where buffers overlap, memmove should be used
instead.
=> Use memmove instead of memcpy when the buffer pointers overlap

m68k_in.c, m68kcpu.c, m68kcpu.h
The first from mame to call line f instead of illegal instruction on cpus without pmmu
and mine to move reset_cycles to the cpu context so that it survives a context switch.
=> 2 fixes for the previous patches

Makefile, example/Makefile, m68kcpu.c, m68kcpu.h, m68kdasm.c, m68kfpu.c, m68kmake.c, softfloat/README.txt, softfloat/mamesf.h, softfloat/milieu.h, softfloat/softfloat-macros, softfloat/softfloat-specialize, softfloat/softfloat.c, softfloat/softfloat.h
the biggest part here is the usage of softfloat, from a lib found on the web.
But it's better to use the mame version because the one from the web has 1 makefile + some headers / target platform, + the latest version has a ton of files, here this version is much smaller and compiles assuming you just change the basic types in softload/mamesf.h (I changed the file to use the current basic types from musashi).
I changed the define for the basic types to typedef but it was useless after all, I can revert to the old defines if you prefer but softfloat is using typedefs anyway so you need a compiler supporting that.
The softfloat lib allows to have some support for the special formats which were not supported before, the surprise is that it seems as fast as before, it's less readable though …
=> big fpu update

m68k_in.c, m68kfpu.c
(same as https://github.com/kstenerud/Musashi/pull/73 with one bug fixed, merged from latest fpu source where same changes were made around "case 0x1e:		// FGETEXP" line and indentation matching previous version to avoid too many diffs)
m68k_in.c (Fixes #70)
fixed all CHK2/CMP2 instructions to support signed bounds. Previously it only worked with unsigned. Also sped up a bit
by changing | by || in Z evaluation formula
cptrapcc opcodes are still unsupported, but if no exception occurs, at least PC is properly updated
trapt/trapcc 16 & 32 instructions: PC is updated before exception is triggered (or if exception isn't triggered). This fixes the
return address value (just in case code returns from trap with RTE) and also the stackframe (XDAda 68040 compiler
read the data parameter to check …
=> misc instructions fixes & additions

m68k_in.c, m68kcpu.c, m68kdasm.c, m68kfpu.c, m68kmake.c, m68kmmu.h, softfloat/softfloat-specialize
The first two commits are strictly speaking bugfixes, where constant strings were concatenated due to missing commas.
The other three are just polish.
=> Minor fixes to keep modern compilers happy

m68kcpu.c
Number of cycles reported by m68k_execute() was incorrect if  m68k_modify_timeslice() was used.
This bug was introduced by the last change done to fix the cycle count if m68k_end_timeslice() was used.
Value return is now correct if m68k_end_timeslice() or m68k_modify_timeslice() is used.
=> Correct cycle count returned by m68k_execute
